version: '3'

services:
  react:
    image: 'upcoderk/react-image'
    build:
      context: front2
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

  spring:
    image: 'upcoderk/myapp'
    build:
      context: project_1
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
