version: '3'

services:
  react:
    image: upcoder/react-image
    volumes:
      - ./front2:/app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  spring:
    image: upcoder/myapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
