version: '3'

services:
  react:
    container_name: react
    image: 'upcoderk/react-image'
    build:
      context: front2
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - "http.cors.allow-origin=http://3.35.179.46:8080"
      - "http.cors.enabled=true"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization,XMLHttpRequest"
      - "http.cors.allow-credentials=true"
    networks: 
      - react
      - spring

  spring:
    container_name: spring
    image: 'upcoderk/myapp'
    build:
      context: project_1
      dockerfile: Dockerfile
    # command:
    #   - run
    #   - --cors 
    #   - "*"
    ports:
      - 8080:8080
    networks: 
      - spring

networks: 
  react:
  spring:
