version: '3'

services:
  react:
    container_name: react
    image: 'upcoderk/react-image'
    build:
      context: front2
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks: 
      - react
      - spring

  spring:
    container_name: spring
    image: 'upcoderk/myapp'
    build:
      context: project_1
      dockerfile: Dockerfile
    # command:
    #   - run
    #   - --cors 
    #   - "*"
    ports:
      - 8080:8080
    networks: 
      - spring

networks: 
  frontend:
  backend:
